[server]
port = 8501
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"  
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false

[logger]
level = "info"
